
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfvrqvmrzbuoizezhxmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdnJxdm1yemJ1b2l6ZXpoeG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0Mjc4MjcsImV4cCI6MjA1NzAwMzgyN30.RRrbTD5c6q32jbJbncWa0m9ZrLFlW0QGH5R4pBF9gBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
